<?php

return [
    'ARG' => ['country_code' => 'ARG', 'flag_path' => 'flags/arg.svg'],
    'AUS' => ['country_code' => 'AUS', 'flag_path' => 'flags/aus.svg'],
    'BEL' => ['country_code' => 'BEL', 'flag_path' => 'flags/bel.svg'],
    'BRA' => ['country_code' => 'BRA', 'flag_path' => 'flags/bra.svg'],
    'CAM' => ['country_code' => 'CMR', 'flag_path' => 'flags/cam.svg'],
    'CAN' => ['country_code' => 'CAN', 'flag_path' => 'flags/can.svg'],
    'CRC' => ['country_code' => 'CRC', 'flag_path' => 'flags/crc.svg'],
    'COS' => ['country_code' => 'CRC', 'flag_path' => 'flags/crc.svg'],
    'CRO' => ['country_code' => 'HRV', 'flag_path' => 'flags/cro.svg'],
    'DEN' => ['country_code' => 'DNK', 'flag_path' => 'flags/den.svg'],
    'ECU' => ['country_code' => 'ECU', 'flag_path' => 'flags/ecu.svg'],
    'ENG' => ['country_code' => 'ENG', 'flag_path' => 'flags/eng.svg'],
    'ESP' => ['country_code' => 'ESP', 'flag_path' => 'flags/esp.svg'],
    'FRA' => ['country_code' => 'FRA', 'flag_path' => 'flags/fra.svg'],
    'GER' => ['country_code' => 'DEU', 'flag_path' => 'flags/ger.svg'],
    'GHA' => ['country_code' => 'GHA', 'flag_path' => 'flags/gha.svg'],
    'IRN' => ['country_code' => 'IRN', 'flag_path' => 'flags/irn.svg'],
    'JPN' => ['country_code' => 'JPN', 'flag_path' => 'flags/jpn.svg'],
    'KOR' => ['country_code' => 'KOR', 'flag_path' => 'flags/kor.svg'],
    'KSA' => ['country_code' => 'SAU', 'flag_path' => 'flags/ksa.svg'],
    'MAR' => ['country_code' => 'MAR', 'flag_path' => 'flags/mar.svg'],
    'MEX' => ['country_code' => 'MEX', 'flag_path' => 'flags/mex.svg'],
    'NED' => ['country_code' => 'NLD', 'flag_path' => 'flags/ned.svg'],
    'POL' => ['country_code' => 'POL', 'flag_path' => 'flags/pol.svg'],
    'POR' => ['country_code' => 'PRT', 'flag_path' => 'flags/por.svg'],
    'QAT' => ['country_code' => 'QAT', 'flag_path' => 'flags/qat.svg'],
    'SEN' => ['country_code' => 'SEN', 'flag_path' => 'flags/sen.svg'],
    'SER' => ['country_code' => 'SRB', 'flag_path' => 'flags/ser.svg'],
    'SUI' => ['country_code' => 'CHE', 'flag_path' => 'flags/sui.svg'],
    'TUN' => ['country_code' => 'TUN', 'flag_path' => 'flags/tun.svg'],
    'URU' => ['country_code' => 'URY', 'flag_path' => 'flags/uru.svg'],
    'USA' => ['country_code' => 'USA', 'flag_path' => 'flags/usa.svg'],
    'WAL' => ['country_code' => 'WAL', 'flag_path' => 'flags/wal.svg'],
];
